"""initial schema

Revision ID: 1c2319364b65
Revises: 
Create Date: 2026-08-08 19:04:12.168855
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op



revision: str = '1c2319364b65'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authors'))
    )
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authors_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_authors_normalized_name'), ['normalized_name'], unique=True)

    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('relations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('normalized_name', 'entity_type', name='uq_entities_name_type')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index('ix_entities_type_mentions', ['entity_type', 'mention_count'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('avg_sentiment', sa.Float(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('centroid', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    comment='Story clusters detected across sources'
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_key'), ['event_key'], unique=True)
        batch_op.create_index('ix_events_first_seen', ['first_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_first_seen_at'), ['first_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_importance'), ['importance'], unique=False)
        batch_op.create_index('ix_events_importance_last_updated', ['importance', 'last_updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_last_updated_at'), ['last_updated_at'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=160), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_scheduled', ['scheduled_for'], unique=False)
        batch_op.create_index('ix_jobs_status_type', ['status', 'job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_target'), ['target'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('homepage', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('category', sa.String(length=48), nullable=True),
    sa.Column('api_key_env', sa.String(length=64), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('request_delay_seconds', sa.Float(), nullable=False),
    sa.Column('max_articles_per_run', sa.Integer(), nullable=False),
    sa.Column('respect_robots', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('total_articles', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    comment='Registry of configured news sources'
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_sources_status'), ['status'], unique=False)
        batch_op.create_index('ix_sources_status_kind', ['status', 'kind'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('parent_slug', sa.String(length=64), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_parent_slug'), ['parent_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_slug'), ['slug'], unique=True)

    op.create_table('trend_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_key', sa.String(length=160), nullable=False),
    sa.Column('subject_label', sa.String(length=200), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_hours', sa.Integer(), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.Column('previous_count', sa.Integer(), nullable=False),
    sa.Column('growth_percent', sa.Float(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=12), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('avg_sentiment', sa.Float(), nullable=False),
    sa.Column('sentiment_delta', sa.Float(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('sample_article_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trend_snapshots')),
    sa.UniqueConstraint('subject_type', 'subject_key', 'window_start', name='uq_trend_subject_window')
    )
    with op.batch_alter_table('trend_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trend_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trend_snapshots_subject_key'), ['subject_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_trend_snapshots_subject_type'), ['subject_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_trend_snapshots_trend_score'), ['trend_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_trend_snapshots_window_start'), ['window_start'], unique=False)
        batch_op.create_index('ix_trend_type_score', ['subject_type', 'trend_score'], unique=False)
        batch_op.create_index('ix_trend_window_score', ['window_start', 'trend_score'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    comment='Platform users'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('min_articles', sa.Integer(), nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.Column('min_relevance', sa.Float(), nullable=False),
    sa.Column('sentiment_filter', sa.String(length=16), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('destination', sa.String(length=2048), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_alerts_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=160), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('category', sa.String(length=48), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('title_hash', sa.String(length=64), nullable=False),
    sa.Column('simhash', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=20), nullable=False),
    sa.Column('sentiment_confidence', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('readability_score', sa.Float(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('enrichment', sa.JSON(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_score', sa.Float(), nullable=True),
    sa.Column('duplicate_method', sa.String(length=32), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 1', name=op.f('ck_articles_relevance_range')),
    sa.CheckConstraint('sentiment_score >= -1 AND sentiment_score <= 1', name=op.f('ck_articles_sentiment_range')),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('fk_articles_author_id_authors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['articles.id'], name=op.f('fk_articles_duplicate_of_id_articles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_articles_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('canonical_url', name='uq_articles_canonical_url'),
    sa.UniqueConstraint('content_hash', name='uq_articles_content_hash'),
    comment='Canonical, de-duplicated news articles'
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_category'), ['category'], unique=False)
        batch_op.create_index('ix_articles_category_published', ['category', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_duplicate_of_id'), ['duplicate_of_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_is_duplicate'), ['is_duplicate'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_language'), ['language'], unique=False)
        batch_op.create_index('ix_articles_language_published', ['language', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_published_at'), ['published_at'], unique=False)
        batch_op.create_index('ix_articles_published_desc', ['published_at'], unique=False)
        batch_op.create_index('ix_articles_relevance', ['relevance_score'], unique=False)
        batch_op.create_index('ix_articles_sentiment', ['sentiment_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_sentiment_label'), ['sentiment_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_simhash'), ['simhash'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_source_id'), ['source_id'], unique=False)
        batch_op.create_index('ix_articles_source_published', ['source_id', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_status'), ['status'], unique=False)
        batch_op.create_index('ix_articles_status_published', ['status', 'published_at'], unique=False)
        batch_op.create_index('ix_articles_title_hash', ['title_hash'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=160), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('resource', sa.String(length=160), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    comment='Append-only audit trail'
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action_time', ['action', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_audit_user_time', ['user_id', 'created_at'], unique=False)

    op.create_table('source_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('articles_fetched', sa.Integer(), nullable=False),
    sa.Column('articles_valid', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_health_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_health')),
    comment='Per-run health samples for each source'
    )
    with op.batch_alter_table('source_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_health_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_health_source_id'), ['source_id'], unique=False)
        batch_op.create_index('ix_source_health_source_time', ['source_id', 'checked_at'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('excluded_sources', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('countries', sa.JSON(), nullable=False),
    sa.Column('sentiment_preference', sa.String(length=16), nullable=False),
    sa.Column('min_relevance', sa.Float(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences'))
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('alert_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('article_ids', sa.JSON(), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('delivery_error', sa.String(length=512), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_triggers_alert_id_alerts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_triggers'))
    )
    with op.batch_alter_table('alert_triggers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_triggers_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index('ix_alert_triggers_alert_time', ['alert_id', 'triggered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_triggers_triggered_at'), ['triggered_at'], unique=False)

    op.create_table('article_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('mentions', sa.Integer(), nullable=False),
    sa.Column('salience', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_entities_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_article_entities_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_entities')),
    sa.UniqueConstraint('article_id', 'entity_id', name='uq_article_entities_pair')
    )
    with op.batch_alter_table('article_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_entities_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_entities_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index('ix_article_entities_entity_salience', ['entity_id', 'salience'], unique=False)

    op.create_table('article_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_topics_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_article_topics_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_topics')),
    sa.UniqueConstraint('article_id', 'topic_id', name='uq_article_topics_pair')
    )
    with op.batch_alter_table('article_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_topics_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_topics_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index('ix_article_topics_topic_score', ['topic_id', 'score'], unique=False)

    op.create_table('event_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_event_articles_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_articles_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_articles')),
    sa.UniqueConstraint('event_id', 'article_id', name='uq_event_articles_pair')
    )
    with op.batch_alter_table('event_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_articles_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_articles_event_id'), ['event_id'], unique=False)
        batch_op.create_index('ix_event_articles_event_similarity', ['event_id', 'similarity'], unique=False)

    op.create_table('saved_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_saved_articles_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_articles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_articles')),
    sa.UniqueConstraint('user_id', 'article_id', name='uq_saved_articles_pair')
    )
    with op.batch_alter_table('saved_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_articles_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_articles_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_saved_articles_user_time', ['user_id', 'saved_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_articles', schema=None) as batch_op:
        batch_op.drop_index('ix_saved_articles_user_time')
        batch_op.drop_index(batch_op.f('ix_saved_articles_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_articles_article_id'))

    op.drop_table('saved_articles')
    with op.batch_alter_table('event_articles', schema=None) as batch_op:
        batch_op.drop_index('ix_event_articles_event_similarity')
        batch_op.drop_index(batch_op.f('ix_event_articles_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_articles_article_id'))

    op.drop_table('event_articles')
    with op.batch_alter_table('article_topics', schema=None) as batch_op:
        batch_op.drop_index('ix_article_topics_topic_score')
        batch_op.drop_index(batch_op.f('ix_article_topics_topic_id'))
        batch_op.drop_index(batch_op.f('ix_article_topics_article_id'))

    op.drop_table('article_topics')
    with op.batch_alter_table('article_entities', schema=None) as batch_op:
        batch_op.drop_index('ix_article_entities_entity_salience')
        batch_op.drop_index(batch_op.f('ix_article_entities_entity_id'))
        batch_op.drop_index(batch_op.f('ix_article_entities_article_id'))

    op.drop_table('article_entities')
    with op.batch_alter_table('alert_triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_triggers_triggered_at'))
        batch_op.drop_index('ix_alert_triggers_alert_time')
        batch_op.drop_index(batch_op.f('ix_alert_triggers_alert_id'))

    op.drop_table('alert_triggers')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_preferences_created_at'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('source_health', schema=None) as batch_op:
        batch_op.drop_index('ix_source_health_source_time')
        batch_op.drop_index(batch_op.f('ix_source_health_source_id'))
        batch_op.drop_index(batch_op.f('ix_source_health_checked_at'))

    op.drop_table('source_health')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user_time')
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_action_time')

    op.drop_table('audit_logs')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('ix_articles_title_hash')
        batch_op.drop_index('ix_articles_status_published')
        batch_op.drop_index(batch_op.f('ix_articles_status'))
        batch_op.drop_index('ix_articles_source_published')
        batch_op.drop_index(batch_op.f('ix_articles_source_id'))
        batch_op.drop_index(batch_op.f('ix_articles_simhash'))
        batch_op.drop_index(batch_op.f('ix_articles_sentiment_label'))
        batch_op.drop_index('ix_articles_sentiment')
        batch_op.drop_index('ix_articles_relevance')
        batch_op.drop_index('ix_articles_published_desc')
        batch_op.drop_index(batch_op.f('ix_articles_published_at'))
        batch_op.drop_index('ix_articles_language_published')
        batch_op.drop_index(batch_op.f('ix_articles_language'))
        batch_op.drop_index(batch_op.f('ix_articles_is_duplicate'))
        batch_op.drop_index(batch_op.f('ix_articles_external_id'))
        batch_op.drop_index(batch_op.f('ix_articles_duplicate_of_id'))
        batch_op.drop_index(batch_op.f('ix_articles_created_at'))
        batch_op.drop_index(batch_op.f('ix_articles_country'))
        batch_op.drop_index('ix_articles_category_published')
        batch_op.drop_index(batch_op.f('ix_articles_category'))
        batch_op.drop_index(batch_op.f('ix_articles_author_id'))

    op.drop_table('articles')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))
        batch_op.drop_index('ix_alerts_user_active')
        batch_op.drop_index(batch_op.f('ix_alerts_is_active'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('trend_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_trend_window_score')
        batch_op.drop_index('ix_trend_type_score')
        batch_op.drop_index(batch_op.f('ix_trend_snapshots_window_start'))
        batch_op.drop_index(batch_op.f('ix_trend_snapshots_trend_score'))
        batch_op.drop_index(batch_op.f('ix_trend_snapshots_subject_type'))
        batch_op.drop_index(batch_op.f('ix_trend_snapshots_subject_key'))
        batch_op.drop_index(batch_op.f('ix_trend_snapshots_created_at'))

    op.drop_table('trend_snapshots')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_slug'))
        batch_op.drop_index(batch_op.f('ix_topics_parent_slug'))
        batch_op.drop_index(batch_op.f('ix_topics_created_at'))

    op.drop_table('topics')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index('ix_sources_status_kind')
        batch_op.drop_index(batch_op.f('ix_sources_status'))
        batch_op.drop_index(batch_op.f('ix_sources_slug'))
        batch_op.drop_index(batch_op.f('ix_sources_language'))
        batch_op.drop_index(batch_op.f('ix_sources_enabled'))
        batch_op.drop_index(batch_op.f('ix_sources_created_at'))
        batch_op.drop_index(batch_op.f('ix_sources_country'))
        batch_op.drop_index(batch_op.f('ix_sources_category'))

    op.drop_table('sources')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_target'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_created_at'))
        batch_op.drop_index('ix_jobs_status_type')
        batch_op.drop_index('ix_jobs_scheduled')

    op.drop_table('processing_jobs')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_last_updated_at'))
        batch_op.drop_index('ix_events_importance_last_updated')
        batch_op.drop_index(batch_op.f('ix_events_importance'))
        batch_op.drop_index(batch_op.f('ix_events_first_seen_at'))
        batch_op.drop_index('ix_events_first_seen')
        batch_op.drop_index(batch_op.f('ix_events_event_key'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))

    op.drop_table('events')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entities_type_mentions')
        batch_op.drop_index(batch_op.f('ix_entities_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_entities_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_entities_entity_type'))
        batch_op.drop_index(batch_op.f('ix_entities_created_at'))

    op.drop_table('entities')
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_authors_created_at'))

    op.drop_table('authors')
    # ### end Alembic commands ###
